spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: root
    password: 123456789admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  token:
    secret: secret123456789
    issuer: BackendService
